#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

#sudo apt-get update
#sudo apt-get install -y nginx
sudo chmod -R 755 /var/www/
echo "Hello World" > /var/www/html/index.html
sudo chmod 766 /etc/nginx/sites-available/default
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx reload
