#!/usr/bin/env bash
# Configure your Nginx server to redirect to another page

sudo apt-get update
sudo apt-get install -y nginx
sudo chmod -R 755 /var/www/
echo "Hello World" | sudo tee -a /var/www/html/index.nginx_debian.html
sudo chown -R $USER:$USER /etc/nginx/sites-enabled/default
sudo chmod 766 /etc/nginx/sites-enabled/default
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
