#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.

sudo apt-get update
sudo apt-get install -y nginx
sudo chmod -R 755 /var/www/

echo "Hello World" | sudo tee /var/www/html/nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo chmod 766 /etc/nginx/sites-available/default

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
location /redirect_me {
        return 301 http://www.youtube.com/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
